services:
  api-principal:
    build: .
    image: globalphone-compare-api
    container_name: globalphone-api
    ports:
      - "5000:5000"
    environment:
      - COMPARACAO_SERVICE_URL=http://api-secundaria:5001
    depends_on:
      - api-secundaria

  api-secundaria:
    build:
      context: ../../Globalphone-compare-service
    image: globalphone-compare-service
    container_name: globalphone-service
    ports:
      - "5001:5001"
    environment:
      - API_PRINCIPAL_URL=http://api-principal:5000